# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Mixture": "01_Mixture_Distribution.ipynb"}

modules = ["mixture.py"]

doc_url = "https://Dzeiberg.github.io/syntheticDataGen/"

git_url = "https://github.com/Dzeiberg/syntheticDataGen/tree/master/"

def custom_doc_links(name): return None
